# Generated by Django 2.0.7 on 2019-04-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerquestion_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionquiz_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerquestion_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionquiz_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(max_length=30),
        ),
    ]
