# Generated by Django 2.0.7 on 2019-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190423_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res', models.CharField(choices=[('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete')], max_length=30)),
            ],
        ),
    ]
