# Generated by Django 2.0.7 on 2019-06-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_multiplechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predefinedanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preanswer1', models.CharField(max_length=120)),
                ('preanswer2', models.CharField(max_length=120)),
                ('preanswer3', models.CharField(max_length=120)),
                ('preanswer4', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answerquestion_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionquiz_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='predefinedanswer',
            name='answerquestion_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
