# Generated by Django 2.0.7 on 2019-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190604_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
