# Generated by Django 2.0.7 on 2019-09-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_quiz_quiz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=120)),
                ('answer1', models.CharField(max_length=120)),
                ('answer2', models.CharField(max_length=120)),
                ('answer3', models.CharField(max_length=120)),
                ('answer4', models.CharField(max_length=120)),
                ('correctone', models.CharField(max_length=120)),
                ('questionquiz_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz')),
            ],
        ),
    ]
